### ISSUE TITLE
A notice from the console during start up

### ISSUE THREAD

**Issue by EmanYm** [KittehOrg/Spectastic#2]
`[Server thread/WARN] [Sponge]: A custom DataBuilder is not extending AbstractDataBuilder! It is recommended that the custom data builder does extend it to gain automated content versioning updates and maintain simplicity. The offending builder's class is: class org.kitteh.spectastic.data.gamemode.PastGameModeDataManipulatorBuilder`

Spongeforge v5.2.0β2320
Spectastic v1.1.0

**Comment by EmanYm** [comment]
Any progress on this?  I'm getting two of these, by the way.
One for `org.kitteh.spectastic.data.gamemode.PastGameModeDataManipulatorBuilder`
and the other for `org.kitteh.spectastic.data.location.PastLocationDataManipulatorBuilder`



Unrelated:
Someone might wonder why I have 1.1.0 when the release version is 1.0.1.  I got 1.1.0 from the mcmod.info file.
>`[`
`    {`
`        "modid": "spectastic",`
`        "name": "Spectastic",`
`        "version": "1.1.0-SNAPSHOT",`
`        "requiredMods": [`
`            "spongeapi@5.0.0"`
`        ]`
`    }`
`]`

**Comment by mbax** [comment]
1.1.1 will make that complaint go away. That message you're getting doesn't make the plugin not work, though.

**Comment by mbax** [comment]
https://ore.spongepowered.org/mbaxter/Spectastic/versions/1.1.1

**Comment by EmanYm** [comment]
I know it doesn't break anything.  It's just that my brain complains if I see any orange "Warn" lines. :P
Thank you for fixing it.

**Comment by mbax** [comment]
My brain complains too! I completely forgot about this issue. :D
